### ISSUE TITLE
KHR_materials_diffuse_transmission: diffuseTransmissionFactor implementation is not consistent with Khronos Sampler viewer

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/Babylon.js#16211]
There is visual inconsistency between the Babylon implementation for KHR_materials_diffuse_transmission  and the one done in the in The Khronos Sample viewer based on the values for diffuseTransmissionFactor. 

According to the spec, "diffuseTransmissionFactor: The percentage of non-specularly reflected light that is diffusely transmitted through the surface.". Therefore, diffuseTransmissionFactor equals 1 means all light should be diffusely transmitted through the surface and none of it should be reflected. The Babylon Sandbox seems to have a behavior of half the light been reflected when the value for diffuseTransmissionFactor = 1. 

Babylon Sandbox: 

![Image](https://github.com/user-attachments/assets/abf0cf6a-ea6d-4323-94d9-47ec61bd26b0)

Khronos Sample Viewer: 

![Image](https://github.com/user-attachments/assets/32043f6a-3186-4416-942e-cded19de0275)

It seems Babylon Sandbox diffuseTransmissionFactor = 1 is equivalent to Khronos Sample Viewer diffuseTransmissionFactor = 0.5. 

[KHR_materials_diffuse_transmission](https://github.com/KhronosGroup/gltf/tree/main/extensions/2.0/Khronos/KHR_materials_diffuse_transmission)

[GLTF Sample](https://github.com/KhronosGroup/glTF-Sample-Assets/pull/167)

**Comment by echadwick-artist** [comment]
Asset revised slightly to comply with Khronos logo guidelines, shouldn't affect your testing though.

**Comment by sebavan** [comment]
Fixed by #16214

**Comment by bghgary** [comment]
It appears this is not fixed. [Loading in the sandbox](https://sandbox.babylonjs.com/?asset=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/d88097fc213201d26affe34798f490e01ce4935a/Models/DiffuseTransmissionTest/glTF/DiffuseTransmissionTest.gltf) still looks like the original image.

**Comment by Popov72** [comment]
Here's what I can see:

Old picture (from @SergioRZMasson first post):
![Image](https://github.com/user-attachments/assets/be544eba-50d6-4c21-8008-7512e75969b3)

New display from the sandbox:
![Image](https://github.com/user-attachments/assets/5a4100d8-1af5-4732-9aa7-0dc409a90f7d)

Tested in Chrome, Edge, Firefox on Windows 11. Maybe you have a browser cache problem?

**Comment by emackey** [comment]
I believe the glTF logo should not be visible at all in the bottom-right tile.  With the diffuse transmission raised up to 100%, all of the light is forward-scattered through the material, and none is left to reflect the baseColorTexture with the green glTF logo in it.

**Comment by bghgary** [comment]
Haha, you beat me to it! 🙂

**Comment by Popov72** [comment]
We should be good with this one: #16337

Babylon:

![Image](https://github.com/user-attachments/assets/e40b2a7a-06ed-4b61-a9fa-baf7d04d1c78)

Khronos viewer:

![Image](https://github.com/user-attachments/assets/9053030f-2f30-4e02-a064-ddbe93b46e69)

**Comment by sebavan** [comment]
closed by #16337
