### ISSUE TITLE
babylon.d.ts not up to date with lib.dom.d.ts

### ISSUE THREAD

**Issue by gama410** [BabylonJS/Babylon.js#4108]
The current version of babylon.d.ts has some specifications that are not up to date with Typescript's standards. This triggers a lot of unnecessary warnings when compiling a babylon project (there are no problem at execution time).

[babylon.d.ts](https://github.com/BabylonJS/Babylon.js/blob/master/dist/babylon.d.ts) specifies the **Navigator** and **GamepadPose** interfaces as 
`interface Navigator {
    getVRDisplays: () => any; ...
}`

`interface GamepadPose {
    hasOrientation: boolean;
    hasPosition: boolean;
    position?: Float32Array;
    linearVelocity?: Float32Array;
    linearAcceleration?: Float32Array;
    orientation?: Float32Array;
    angularVelocity?: Float32Array;
    angularAcceleration?: Float32Array;
}`

whereas [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts) specifies them as : 
`interface Navigator extends... {
    getVRDisplays(): Promise<VRDisplay[]>; ...
}`

`interface GamepadPose {
    readonly angularAcceleration: Float32Array | null;
    readonly angularVelocity: Float32Array | null;
    readonly hasOrientation: boolean;
    readonly hasPosition: boolean;
    readonly linearAcceleration: Float32Array | null;
    readonly linearVelocity: Float32Array | null;
    readonly orientation: Float32Array | null;
    readonly position: Float32Array | null;
}`

If babylon's d.ts file redefined these interfaces accordingly, I believe all warnings would disappear...

thanks a lot!

**Comment by deltakosh** [comment]
It is fixed in the dist/preview release folder :)

**Comment by gama410** [comment]
Great!  
I still have a question, though. I got the babylonjs package through npm and  I only get the basic d.ts (along with other files). Is there a streamlined way of getting the preview release distributable instead of the regular ones?

**Comment by deltakosh** [comment]
The fix will be in next npm package:)

**Comment by gama410** [comment]
Fabulous! Thanks!
