### ISSUE TITLE
Resizing issues with android/ipad on Babylon Playground

### ISSUE THREAD

**Issue by DarrenCook** [BabylonJS/Babylon.js#520]
Wanting to get a feel for webgl performance on mobile, I opened up the playground on a few devices. One minor issue is that all of them have the FPS counter hidden by the FullScreen button (and FPS is not shown in fullscreen).

On Nexus 7 (chrome, android 4.4.4) it seems fine, with or without editor, and in landscape or portrait. But if I add the debug layer, then it only fills a quarter of the screen. [Update: if I put debug layer on, go to full screen, then leave full screen, it uses yet another different screen size, which is wider than the physical screen, so I cannot access some buttons now.]

On cheap Android phone ("browser", which is probably chrome; android 4.2.2) it is mostly OK, especially in landscape. The buttons and links at the bottom take more than their fair share of the screen real estate, though! In Portrait mode the centre of the screen is off the page (and impossible using touch to turn to face the centre!) Fullscreen button is ignored.

On iPad Air 1 (iOS 8.1.2) it is almost exactly like the Nexus: fine in all combinations, until I add the debug layer. Then the screen goes to half height, and just of half width. If I have the editor shown it is about 2/3rds screen width. In portrait, with debug layer and editor on, it is 2/3rds wide, full height; if I hide the editor it becomes half height, just over half width!  FullScreen button is ignored.

One difference might be that the nexus and ipad are high-res screens, so the device pixel and CSS pixel size can be different.

**Comment by Palmer-JC** [comment]
I know.  This happens for me too.  The playground is a developer tool though.  You are never going to distribute your game through the playground.  Also, these devices very often have no keyboard, so they are not very good for typing in your program.

Think there might be higher priorities.

**Comment by RaananW** [comment]
I believe the playground was not developed with responsiveness in mind. As Jeff said, it is a developers tool for "rapid webgl prototyping". 
If you want to check webgl on mobile,  maybe try the main website?

**Comment by deltakosh** [comment]
Absolutely, the intend of the playground is to be used with a mouse/keyboard on a PC/Mac/Linux.
But if you want to contribute and fix the debug layer issue it would be cool:)

**Comment by DarrenCook** [comment]
I like that the playground has export to zip, which you can then use as the starting point for further customization of your site. So it'd be nice if it was mobile-ready. But, yes, I agree it is fairly low priority. (i.e. apart from not being able to see the FPS, it didn't stop me evaluating usability on mobile of the various demos).

**Comment by deltakosh** [comment]
Can you refresh the playground on your devices? I did some responsive improvements (At least for the FPS:))

**Comment by deltakosh** [comment]
For debug layer I would like to understand better the problem because I thought I fixed the deviceRatio issue

**Comment by DarrenCook** [comment]
Sorry for the late response. I did test the changes, and the RWD changes worked, as FPS is now visible. The debug layer is still wrongly sizing.
